dataset_name: SHT
rgb_dataset_path: data/SHT/zwh_rgb.list
train_split: data/SHT/SH_Train_new.txt
test_split: data/SHT/SH_Test_NEW.txt
test_mask_dir: data/SHT/test_frame_mask/
gt: data/SHT/gt-SHT.npy

feature_dim: 1024
out_feature_dim: 2048
layer_num: 3
epochs: 2000
warmup_epochs: 5
eval_epoch: 5
batch_size: 10     # 5 10
gpu0sz: 0.6      #0.6 0.8
test_batch_size: 1     # 20 42
clips_num: 32
segment_len: 16
ten_crop: False
dropout_rate: 0.8

test_gl: False
class_reweights: [0.8,0.65]
label_smoothing: 0
loss_margin: 20
loss_feat_alpha: 0.001   # 0.001
loss_score_alpha: 0.1   # 0.1
loss_aggr_cls: 1

loss_sparse: 0.008
loss_smooth: 0.0008

# optimizer
optimizer: Adam
optimizer_args: {lr: 0.00001, weight_decay: 0.0005, lr_scheduler: None, betas: [0.9, 0.999]}

save_path: ./save/SHT/exp


