dataset_name: XDViolence
rgb_dataset_list: data/XDViolence/zwh_rgb.list
test_rgb_dataset_list: data/XDViolence/zwh_rgb_test.list
gt: data/XDViolence/gt.npy

feature_dim: 1024
out_feature_dim: 2048
layer_num: 3
epochs: 2000
warmup_epochs: 5
eval_epoch: 1
batch_size: 128     # 128
gpu0sz: 0.6      #0.6 0.8
test_batch_size: 5     # 20 42
clips_num: 32
segment_len: 16
ten_crop: False
dropout_rate: 0.8
hard_thres: 0.5

test_gl: False
class_reweights: [1,1]
label_smoothing: 0
loss_margin: 20
loss_feat_alpha: 0   # 0.001
loss_score_alpha: 0.1   # 0.1

loss_sparse: 0   # 0.008
loss_smooth: 0   # 0.0008

# optimizer
optimizer: Adam
optimizer_args: {lr: 0.0001, weight_decay: 0.0005, lr_scheduler: None, betas: [0.9, 0.999]}

save_path: ./save/XD-new


